services:
  database:
    image: timescale/timescaledb:latest-pg17
    container_name: bourse-database
    command: postgres -c shared_preload_libraries=timescaledb
    networks: [ boursenet ]
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=bourse
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb-data:/var/lib/postgresql/data/timescaledb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bourse -d bourse" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bourse-dashboard
    depends_on:
      database:
        condition: service_healthy
    networks: [ boursenet ]
    ports:
      - "8050:8050"
    restart: on-failure:3
    volumes:
      - ./data:/mnt/data:ro

volumes:
  timescaledb-data:

networks:
  boursenet:
    driver: bridge
