services:
  database:
    image: timescale/timescaledb:latest-pg17
    container_name: bourse-database
    command: postgres -c shared_preload_libraries=timescaledb
    restart: unless-stopped
    networks: [ boursenet ]
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=bourse
      - POSTGRES_PASSWORD=password
    volumes:
      - timescaledb-data:/var/lib/postgresql/data/timescaledb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bourse -d bourse" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bourse-dashboard
    depends_on:
      database:
        condition: service_healthy
    networks: [ boursenet ]
    environment:
      - EURONEXT_START=${EURONEXT_START:-2020-05-01}
      - EURONEXT_END=${EURONEXT_END:-2022-09-16}
      - BOURSO_START=${BOURSO_START:-2020-01-01}
      - BOURSO_END=${BOURSO_END:-2022-01-01}
    ports:
      - "8050:8050"
    restart: on-failure:10
    volumes:
      - ./data:/mnt/data:ro

volumes:
  timescaledb-data:

networks:
  boursenet:
    driver: bridge
